### ISSUE TITLE
Null reference when trying to ReadAllTextAsync

### ISSUE THREAD

**Issue by Kirbyrawr** [richardschneider/net-ipfs-engine#17]
Hi there, i wanted to read text from a cid but it's giving me null references in FileSystem.cs
I didn't have any problem using the api and the daemon, but yes with the engine.

Here's a sample code that will throw the error:

```
await ipfs.StartAsync();
string text = await ipfs.FileSystem.ReadAllTextAsync("QmRknUwtMgvFftbA7MhN2jf1yqWUt26U61F8zWpZgiDjst");
Console.WriteLine(text);
```

![image 2](https://user-images.githubusercontent.com/3259762/40591495-a1cd122a-6212-11e8-9d19-f3a18128f62c.png)

**Comment by richardschneider** [comment]
This is still **alpha code** and a lot of things are still not yet implemented.  Two majors components are not there yet `Swarm` and `Bitswap`.  This means that getting a block/file from the peer network is not working.

I'll change the code to throw an exception when `Bitswap`  is needed, instead of returning null.

**Comment by Kirbyrawr** [comment]
Thank you for the hint!

**Comment by richardschneider** [comment]
Bitswap and DHT are now implemented, so fetching a file from the IPFS network should work!

If you still want to contribute, I would be **glad** to have your help.  I'm makaretu at gmail dot com. My timezone is UTC+12

**Comment by richardschneider** [comment]
No response from @Kirbyrawr
